### ISSUE TITLE
Feature Request - send epub to kindle

### ISSUE THREAD

**Issue by kmorber** [mikespub-org/rvolz-BicBucStriim#2]
Hello,

will it be possible to send epub files to kindle?

BR

Karsten

**Comment by mikespub** [comment]
That should already be supported when you specify an e-mail address in /admin/configuration/, thanks to https://github.com/mikespub-org/rvolz-BicBucStriim/pull/1 It's included in release 1.6.6 and later

If it doesn't, please post the complete error message in here so I can find out what happened...

**Comment by kmorber** [comment]
Perfect, Thank you!!

**Comment by mikespub** [comment]
Oops, please be aware: sometime between 1.6.6 and 1.7.2 I messed up the e-mail validation check:
https://github.com/mikespub-org/rvolz-BicBucStriim/blob/0d27cf80b618498695750e55446430468fecb9ee/src/Actions/admin.php#L437

This should read:
```php
        } elseif (!Utilities::isEMailValid($req_configs[KINDLE_FROM_EMAIL])) {
```

with a **!** at the beginning of the `elseif (...)` part:  `elseif (!...)`
