### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by Borogroves** [mikespub-org/rvolz-BicBucStriim#4]
Thanks for maintaining this fork. I'm running bbs on Synology DSM 7.2 (recently updated from 6.x).

I installed the package from DSM Package Center, and entered the Calibre library path (/volume1/Calibre). Then I ran installcheck.php and all checks passed. htaccess exists in bbs folder.

At this point, I can open the bbs app from the browser, and download books.

I added the OPDS feed URL to Thorium. The catalog opens and I'm able to browse. But when attempting to download a file, the following error occurs:

`Downloading failed: [[AssertionError [ERR_ASSERTION]: http GET error: Internal Server Error (500)`

I enabled debug mode and noticed that the 'book: size' has values when downloading from the browser, but no values when attempting to download from Thorium (or any other OPDS compatible app). I went hunting in /var/services/tmp and found temp files. For the ebook downloaded from the browser. the temp file was the same size as the ebook file - as expected. For the attempts from Thorium, the temp files exist but have a size 0. I verified that the user can write files in the tmp folder by running `sudo -u sc-bicbucstriim touch /volume1/@tmp/testfile`

So the issue seems isolated to how bbs is handling OPDS downloads, particularly in how it manages temp files during the OPDS download process, where the temp file sizes are consistently 0.

DSM version: 7.2
BBS version: 3.4.2
PHP version: 8.2
PHP extensions installed: gd, intl, pdo_sqlite, sodium, sqlite3
open_basedir: /volume1/web_packages/bbs:/volume1/Calibre:/var/services/tmp
Calibre folder has permission 777

What am I missing?

**Comment by mikespub** [comment]
Hi @Borogroves sorry to hear that.

From what I understand, you already covered all the basic checks, so we'll need to investigate a bit further...

Are you using Apache as http back-end server for WebStation in DSM, and is there anything in the Apache error logfile that might shed a light on the actual problem? It should be under `/var/packages/Apache2.4/var/log`

You also mention that this problem only happens when trying to download a book with Thorium. Did you configure BBS to update  the metadata before downloading, and are you using relative URLs or not?

**Comment by mikespub** [comment]
Another question: if you go to `/bbs/opds/newest/` in your browser you should see XML output with file entries like:

```xml
<entry>
   ...
  <link href="/bbs/data/titles/thumb_13012.png" type="image/png" rel="http://opds-spec.org/image/thumbnail"/>
  <link href="/bbs/titles/13012/cover/" type="image/jpeg" rel="http://opds-spec.org/image"/>
  <link href="/bbs/titles/13012/file/My+Book+Title+-+My+Author.epub" type="application/epub+zip" rel="http://opds-spec.org/acquisition"/>
</entry>
```

Is that what you also see or not?

**Comment by Borogroves** [comment]
Hi @mikespub thanks for the pointers.

Yes, I'm using Apache 2.4

In BBS, Update metadata and Relative URLs are both off. I've tried every combo of on/off with them; same result with the 500 error.

When I go to `/bbs/opds/newest/` in the browser, an XML file gets downloaded. The last link is the ebook:
`http://192.168.2.110/bbs/titles/1/file/stranger+-+Camus.epub`

When I put that into the browser, I get a 500 error.

The actual file in the Calibre library has spaces instead of '+' signs:
`http://192.168.2.110/bbs/titles/1/file/stranger - Camus.epub`

When I put that into the browser, the file does download. 
And when I rename the file to match what's in the XML (ie, replace spaces with '+'), the file also downloads.

The Apache log shows that BBS is using the link with the '+', and hence not finding the file.
2024-10-19T09:06:19-04:00 Synology [Sat Oct 19 09:06:19.951681 2024] [proxy_fcgi:error] [pid 16187:tid 140309124015808] [client 192.168.2.254:60904] AH01071: Got error 
PHP message: PHP Warning:  stat(): stat failed for /volume1/CalibreTEST/Camus/stranger (1)/stranger+-+Camus.epub in /volume1/web_packages/bbs/src/Utilities/CalibreUtil.php on line 27;
PHP message: PHP Warning:  filesize(): stat failed for /volume1/CalibreTEST/Camus/stranger (1)/stranger+-+Camus.epub in /volume1/web_packages/bbs/src/Actions/MainActions.php on line 471;
PHP message: PHP Warning:  filesize(): stat failed for /volume1/CalibreTEST/Camus/stranger (1)/stranger+-+Camus.epub in /volume1/web_packages/bbs/src/Traits/AppTrait.php on line 392;
PHP message: Slim Application Error
Type: RuntimeException\nCode: 0
Message: The file "/volume1/CalibreTEST/Camus/stranger (1)/stranger+-+Camus.epub" cannot be opened: fopen(/volume1/CalibreTEST/Camus/stranger (1)/stranger+-+Camus.epub): Failed to open stream: No such file or directory
File: /volume1/web_packages/bbs/vendor/nyholm/psr7/src/Factory/Psr17Factory.php
Line: 49
Trace: #0 /volume1/web_packages/bbs/src/Traits/AppTrait.php(394): Nyholm\\Psr7\\Factory\\Psr17Factory->createStreamFromFile('/volume1/Calibr...')
#1 /volume1/web_packages/bbs/src/Actions/MainActions.php(473): BicBucStriim\\Actions\\DefaultActions->mkSendFileAsAttachment('/volume1/Calibr...', 'application/epu...', 'stranger+-+Camu...')
#2 /volume1/web_packages/bbs/src/Utilities/ActionsWrapperStrategy.php(35): BicBucStriim\\Actions\\MainActions->book('1', 'stranger+-+Camu...')
#3 /volume1/web_packages/bbs/vendor/slim/slim/Slim/Routing/Route.php(363): BicBucStriim\\Utilities\\ActionsWrapperStrategy->__invoke(Array, Object(Nyholm\\Psr7\\ServerRequest),...'


Using ChatGPT, I edited the bookPath function in CalibreUtil.php. I enclosed '$file' in a urldecode() function, rebooted the NAS, and it worked! That might not be the optimal fix, but I think it at least confirms the root cause as being url handling, right?

**Comment by mikespub** [comment]
Excellent work, thanks! It seems Thorium doesn't support "old-style" +-encoded spaces from PHP [urlencode()](https://www.php.net/manual/en/function.urlencode.php), only %20-encoded spaces from PHP [rawurlencode()](https://www.php.net/manual/en/function.rawurlencode.php). Regular browsers will still translate + into spaces before sending the request, and so their download will work.

In release 3.4.2 you can fix it at the source in 
https://github.com/mikespub-org/rvolz-BicBucStriim/blob/73a86c78e87c9a9ecbda7045960b9b2bd3afe418/src/Utilities/OpdsGenerator.php#L650

by replacing urlencode() with rawurlencode() to generate the right URLs in OPDS feeds for Thorium.

I'll include the fix in the next release - thanks for tracking this down :-)

**Comment by mikespub** [comment]
Included in [release 3.5.2](https://github.com/mikespub-org/rvolz-BicBucStriim/releases/tag/v3.5.2)

**Comment by Borogroves** [comment]
Thanks for the quick fix!

Just to note - the issue wasn't only with Thorium; it was also with Kybook and Cantook.

Anyway, I can confirm that replacing urlencode() with rawurlencode() fixes the issue (I reverted my change in CalibreUtil and instead replaced the function in OpdsGenerator). Makes sense to fix it at the source.

Will the SynoCommunity package get updated automatically? I'm happy to help with testing, etc.

**Comment by mikespub** [comment]
Makes sense, and good to know :-)

Unlike linuxserver.io container images like [docker-cops](https://github.com/linuxserver/docker-cops) which are triggered automatically within the hour after a new release, the SynoCommunity packages need to be updated manually - see https://github.com/SynoCommunity/spksrc/pull/6229 for the previous update.

You might create a new issue or pull request there to request the upgrade to 3.5.2 or later...
