### ISSUE TITLE
value (0101)  default template

### ISSUE THREAD

**Issue by sohanev** [mikespub-org/rvolz-BicBucStriim#6]
Hi, when a book has no publication date, it displays the value (0101)

default template

I would suggest this solution

title_entry

`{% if book.pubdate|date("Y") != "0101" %} `
`<h3> {% if series %}{{book.series_index}} - {% endif %} {{ book.sort }} ({{ book.pubdate|date("Y") }}) </h3> `
`{% else %}` 
`<h3> {% if series %}{{book.series_index}} - {% endif %} {{ book.sort }} </h3> `
`{% endif %}`

title_detail

`{% if book.pubdate|date("Y") != "0101" %} `
`<p>					 {{ book.pubdate | date("Y") }}	{{ language }} </p>`
` {% else %}` 
`<p>					 {{ language }} </p> `
`{% endif %}`

**Comment by mikespub** [comment]
It's a good point, but I would check on the value of book.pubdate itself:

```twig
{% if book.pubdate %}
    {{ book.pubdate|date("Y") }}
{% endif %}
```

Reason is that an empty (or zero) pubdate returns "1970" instead of "0101" on my test site, so your mileage may vary :-)

**Comment by mikespub** [comment]
See [release 3.6.3](https://github.com/mikespub-org/rvolz-BicBucStriim/releases/tag/v3.6.3)
